# Generated by Django 4.1.3 on 2022-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="trait",
        ),
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="trait", to="traits.trait"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Famale", "Female"),
                    ("Not Informed", "Default"),
                ],
                default="Not Informed",
                max_length=12,
            ),
        ),
    ]
