# Generated by Django 4.1.3 on 2022-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
        ("pets", "0002_remove_pet_trait_pet_traits_alter_pet_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="traits", to="traits.trait"),
        ),
    ]
